### ISSUE TITLE
Docs please

### ISSUE THREAD

**Issue by michalzadkowski** [anson-vandoren/esp32-linak-controller#1]
Hey, first and foremost, thanks for putting an effort with controlling Linak desks.

I tried to get your thing running, but failed miserably. I'm not really all that comfortable with programming microcontrollers and Platformio, so probably the blame is on me. However, any documentation or readme would be helpful.
Thanks again!

**Comment by anson-vandoren** [comment]
Thanks for the comment. This is still 100% a work in progress, unfortunately, and there's no actual functionality implemented yet. You're welcome to hack around on it, and I've been working on this project somewhat regularly, but no guarantees.

I'll put a comment in the README to that effect so others don't try to spend too much effort on it until it's more complete.

My ultimate goal with this project is going to be to have

1. A web interface served by the ESP32 to control the basic desk functions
2. A MQTT bridge to relay commands/responses between the desk and my other smart home devices

If you're just looking to control the Linak desk programmatically, and you're happy to use Bluetooth (BLE) to do that, there's quite a few other libraries out there that already allow you to accomplish this.

**Comment by michalzadkowski** [comment]
Thanks for the prompt reply!
I'm happy to say that after a couple of hours of playing with your code I managed to get it running. Well, almost. I presume I got to the very point you reached - the web interface is there, the BT discovery works, desk's name id read, but pairing and actual control is not quite there yet.

Anyway, thanks for the clarification. I'll keep a keen eye on your project.

**Comment by anson-vandoren** [comment]
Thanks, and glad you got a little further with it. Knowing someone else is interested should provide a little more motivation for me to finish this project up :)

**Comment by krzmaz** [comment]
Hey, @anson-vandoren, @michalzadkowski sorry for commenting on an closed issue, but I've found this repo some time ago and decided to ping you guys, when I will achieve some success with my effort: https://github.com/TheRealMazur/LinakDeskEsp32Controller 

I've managed to create a controller for my Ikea Idasen desk with a HTTP API and a basic web interface. There are plans for adding MQTT and maybe some more stuff, but I'm currently working on improving the stability. Check it out if you're still interested in the subject :)

**Comment by anson-vandoren** [comment]
@TheRealMazur thanks! Took a brief look and your project seems really interesting. Hopefully I'll get a chance to dig deeper into it and give it a test next weekend. As you can probably tell from looking at this repo, I haven't had time to get any further on my own implementation :)

**Comment by krzmaz** [comment]
@anson-vandoren BTW thank you very much for documenting your findings about the communication in the other repo! It helped a lot :)
